parameters:
    user_profile_provider.class: Main\LoginBundle\Model\ProfileProvider
    user_profile_provider.fm_data:     %base_parametro%

services:
    user_profile_provider:
        class: %user_profile_provider.class%
        arguments:    ["@service_container"]
